# Generated by Django 6.0.4 on 2026-04-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("binaries", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="version_code",
            field=models.PositiveIntegerField(verbose_name="Code de version"),
        ),
        migrations.AlterField(
            model_name="release",
            name="version_id",
            field=models.CharField(max_length=50, verbose_name="Nom de version (ID)"),
        ),
    ]
