# Generated by Django 6.0.4 on 2026-04-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("binaries", "0004_alter_artifact_hash_and_more"),
        ("projects", "0005_alter_projectinvitation_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="application",
            name="unique_app_per_project",
        ),
        migrations.AddField(
            model_name="application",
            name="app_signature",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Signature de l'application (SHA-256)",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=("project", "app_id", "app_signature"), name="unique_app_per_project"
            ),
        ),
    ]
