# Generated by Django 6.0.4 on 2026-04-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("binaries", "0006_releasemessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="size",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Taille (octets)"
            ),
        ),
    ]
