# Generated by Django 6.0.4 on 2026-04-26 16:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("binaries", "0007_artifact_size"),
        ("projects", "0005_alter_projectinvitation_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, verbose_name="Nom du tag")),
                (
                    "color",
                    models.CharField(default="#6200EE", max_length=7, verbose_name="Couleur (Hex)"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_tags",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="release",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="releases", to="binaries.releasetag"
            ),
        ),
        migrations.AddConstraint(
            model_name="releasetag",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="unique_tag_per_project"
            ),
        ),
    ]
