# Generated by Django 6.0.4 on 2026-04-26 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("binaries", "0009_bugreport_bugmessage_delete_releasemessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bugreport",
            name="title",
        ),
    ]
