# Generated by Django 6.0.4 on 2026-04-26 17:58

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("binaries", "0010_remove_bugreport_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bugmessage",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="bugreport",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
