# Generated by Django 6.0.4 on 2026-04-23 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(("type__in", ["PROJECT_INVITATION", "SYSTEM_ALERT"])),
                name="check_notification_type_valid",
            ),
        ),
    ]
