# Generated by Django 6.0.4 on 2026-04-26 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_remove_notification_check_notification_type_valid_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notification",
            name="check_notification_type_valid",
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("PROJECT_INVITATION", "Invitation à un projet"),
                    ("SYSTEM_ALERT", "Alerte système"),
                    ("APPLICATION_CREATED", "Application créée"),
                    ("APPLICATION_DELETED", "Application supprimée"),
                    ("NEW_RELEASE", "Nouvelle release"),
                    ("NEW_MESSAGE", "Nouveau message"),
                    ("NEW_BUG", "Nouveau bug"),
                ],
                max_length=50,
                verbose_name="Type",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "type__in",
                        [
                            "PROJECT_INVITATION",
                            "SYSTEM_ALERT",
                            "APPLICATION_CREATED",
                            "APPLICATION_DELETED",
                            "NEW_RELEASE",
                            "NEW_MESSAGE",
                            "NEW_BUG",
                        ],
                    )
                ),
                name="check_notification_type_valid",
            ),
        ),
    ]
