# Generated by Django 6.0.4 on 2026-04-17 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprojectprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_project_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userprojectprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'ADMIN')), fields=('project',), name='unique_project_admin'),
        ),
        migrations.AddConstraint(
            model_name='userprojectprofile',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='unique_user_project'),
        ),
    ]
