# Generated by Django 6.0.4 on 2026-04-23 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_projectinvitation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="projectinvitation",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["PENDING", "ACCEPTED", "REJECTED"])),
                name="check_project_invitation_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectinvitation",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["ADMIN", "MEMBER"])),
                name="check_project_invitation_role_valid",
            ),
        ),
    ]
