# Generated by Django 6.0.4 on 2026-04-23 21:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_projectinvitation_check_project_invitation_status_valid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectinvitation",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
