"""add icon_key to Application

Revision ID: 4b5babf792cd
Revises: db212a44f1bb
Create Date: 2026-07-19 13:39:56.412008

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b5babf792cd"
down_revision: str | Sequence[str] | None = "db212a44f1bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "binaries_application",
        sa.Column("icon_key", sa.String(length=500), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("binaries_application", "icon_key")
    # ### end Alembic commands ###
