# Generated by Django 6.0.4 on 2026-04-23 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Utilisateur", "verbose_name_plural": "Utilisateurs"},
        ),
    ]
