# Generated by Django 6.0.4 on 2026-04-18 11:52

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskJob",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("BINARY_PROCESSING", "Traitement de binaire")],
                        max_length=50,
                        verbose_name="Type de tâche",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("STARTED", "En cours"),
                            ("SUCCESS", "Réussite"),
                            ("FAILURE", "Échec"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="PENDING",
                        max_length=50,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Données d'entrée"),
                ),
                (
                    "output_data",
                    models.JSONField(blank=True, default=dict, verbose_name="Données de sortie"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="Message d'erreur"),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Clé d'idempotence"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Démarré le"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Terminé le"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Expire le"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tâche de traitement",
                "verbose_name_plural": "Tâches de traitement",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("started_at__isnull", True),
                            ("started_at__gte", models.F("created_at")),
                            _connector="OR",
                        ),
                        name="check_started_after_created",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("finished_at__isnull", True),
                            ("finished_at__gte", models.F("started_at")),
                            _connector="OR",
                        ),
                        name="check_finished_after_started",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "FAILURE"), _negated=True),
                            models.Q(("error_message", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="check_error_on_failure",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("idempotency_key__isnull", False)),
                        fields=("user", "type", "idempotency_key"),
                        name="unique_user_task_idempotency",
                    ),
                ],
            },
        ),
    ]
