# Generated by Django 6.0.4 on 2026-04-18 11:14

import django.db.models.deletion
import django.utils.timezone
import django_fsm
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskJob',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('BINARY_PROCESSING', 'Traitement de binaire')], max_length=50, verbose_name='Type de tâche')),
                ('status', django_fsm.FSMField(choices=[('PENDING', 'En attente'), ('STARTED', 'En cours'), ('SUCCESS', 'Réussite'), ('FAILURE', 'Échec'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=50, protected=True, verbose_name='Statut')),
                ('input_data', models.JSONField(blank=True, default=dict, verbose_name="Données d'entrée")),
                ('output_data', models.JSONField(blank=True, default=dict, verbose_name='Données de sortie')),
                ('error_message', models.TextField(blank=True, default='', verbose_name="Message d'erreur")),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Démarré le')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Tâche de traitement',
                'verbose_name_plural': 'Tâches de traitement',
                'ordering': ['-created_at'],
            },
        ),
    ]
