# Generated by Django 6.0.4 on 2026-04-18 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskjob',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Clé d'idempotence"),
        ),
        migrations.AddConstraint(
            model_name='taskjob',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__isnull', True), ('started_at__gte', models.F('created_at')), _connector='OR'), name='check_started_after_created'),
        ),
        migrations.AddConstraint(
            model_name='taskjob',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='check_finished_after_started'),
        ),
        migrations.AddConstraint(
            model_name='taskjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'FAILURE'), _negated=True), models.Q(('error_message', ''), _negated=True), _connector='OR'), name='check_error_on_failure'),
        ),
        migrations.AddConstraint(
            model_name='taskjob',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('user', 'type', 'idempotency_key'), name='unique_user_task_idempotency'),
        ),
    ]
